import type { Metadata } from "next";
import "./globals.css";
import CustomRootLayout from "@/components/layout/CustomRootLayout";
import TopNotify from "@/components/home/TopNotify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="cmyk">
      <body
      >
        <TopNotify />
        <CustomRootLayout />
        {children}
      </body>
    </html>
  );
}
